package com.nata.bookspace.bookservice.entity;

public enum Genre {
    FICTION, NONFICTION, MYSTERY, ROMANCE, SCIENCE_FICTION, FANTASY, HORROR, THRILLER, HISTORICAL_FICTION, BIOGRAPHY, AUTOBIOGRAPHY, MEMOIR, SELF_HELP, POETRY, DRAMA, COMEDY, YOUNG_ADULT;
}
